pipeline:

  docker-buikd:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: mcom/docker-php-cs-fixer
    tags: [ "dev"]
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: [ push, pull_request ]

  publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: mcom/docker-php-cs-fixer
    tags: [ "${DRONE_COMMIT_SHA:0:7}", "${DRONE_TAG=latest}" ]
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: [ tag ]